### ISSUE TITLE
a little visual glitch when scrolling

### ISSUE THREAD

**Issue by oceancx** [janisdd/vscode-edit-csv#12]
somehow sometimes the grid line is highlighted when scrolling

**Comment by janisdd** [comment]
I experienced the same but cannot remember under what circumstances. It was monitor specific though... 
I'll keep an eye on this.

**Comment by oceancx** [comment]
my monitor is dell 2417h, i suppose it was the rendering problem not the monitor specific...

**Comment by janisdd** [comment]
With version 1.40 vs code now uses electron 6 (and a new chrome)... maybe the update resolves this issue?

**Comment by oceancx** [comment]
I will have a try now~

**Comment by oceancx** [comment]
sorry, i have tried, but this issue is still exist. I have the same visual glitch no matter whether at home or at my company. both places' display is dell u2417

**Comment by oceancx** [comment]
![微信图片_20191108233546](https://user-images.githubusercontent.com/9250949/68488675-8c3b7e00-0280-11ea-8f47-70cb023b1f2d.png)

the main issue is the horizontal separator is highlighted when you scrolling the content.

**Comment by oceancx** [comment]
![微信图片_20191108233821](https://user-images.githubusercontent.com/9250949/68488829-d9b7eb00-0280-11ea-8a45-03bf70f41e6d.png)
this one is the normal case. can we do something to make the color highlight disappear...

**Comment by janisdd** [comment]
Hm even the vertical lines are too strong... Is this also case for a light theme?
Maybe a setting to set the border width to 0 would do the trick... I'll experiment a bit

**Comment by oceancx** [comment]
you are clever! the light theme is perfect, everything is fine no matter how i scrolling

**Comment by oceancx** [comment]
the website's table view is fine.

**Comment by janisdd** [comment]
It's a bit hacky but you could try the following (to see if it's working):

- switch to a dark theme
- open the file `~/.vscode/extensions/janisdd.vscode-edit-csv-0.2.3/csvEditorHtml/dark.css`
- find the css rules `.vscode-dark .ht_master tr:nth-of-type(odd) > td {` and `.vscode-dark .ht_master tr:nth-of-type(even) > td {`

and replace the body with the following
```css
.vscode-dark .ht_master tr:nth-of-type(odd) > td {
	background-color: #262c2e;
	/* border-color: 1px solid #5c5c5c; */
	border-right: 1px solid #5c5c5c;
	border-bottom: 1px solid #5c5c5c;
	border-left: 1px solid #5c5c5c;
	border-right: 1px solid #5c5c5c;
}

.vscode-dark .ht_master tr:nth-of-type(even) > td {
	background-color: #2d3436;
	/* border-color: #5c5c5c; */
	border-right: 1px solid #5c5c5c;
	border-bottom: 1px solid #5c5c5c;
	border-left: 1px solid #5c5c5c;
	border-right: 1px solid #5c5c5c;
}
```

*Then maybe restart vs code?*

If this does not help, replace the content with 

```css
.vscode-dark .ht_master tr:nth-of-type(odd) > td {
	background-color: #262c2e;
	border: 0;
}

.vscode-dark .ht_master tr:nth-of-type(even) > td {
	background-color: #2d3436;
	border: 0;
}
```

And to revert that here are the original/current rules

```css
.vscode-dark .ht_master tr:nth-of-type(odd) > td {
	background-color: #262c2e;
	border-color: #5c5c5c;
}

.vscode-dark .ht_master tr:nth-of-type(even) > td {
	background-color: #2d3436;
	border-color: #5c5c5c;
}
```
